coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: false
  hide_project_coverage: true

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 1%
        branches:
          - "!main"
  individual_components:
    # Core Architecture Components
    - component_id: core_app
      name: Core Application
      paths:
        - DeepResearch/app.py
        - DeepResearch/__init__.py

    - component_id: agents
      name: Agents
      paths:
        - DeepResearch/agents.py
        - DeepResearch/src/agents/**

    - component_id: datatypes
      name: Data Types
      paths:
        - DeepResearch/src/datatypes/**

    - component_id: tools
      name: Tools
      paths:
        - DeepResearch/tools/**
        - DeepResearch/src/tools/**

    - component_id: statemachines
      name: State Machines
      paths:
        - DeepResearch/src/statemachines/**
        - configs/statemachines/**

    - component_id: utils
      name: Utilities
      paths:
        - DeepResearch/src/utils/**

    - component_id: models
      name: Models
      paths:
        - DeepResearch/src/models/**

    - component_id: prompts
      name: Prompts
      paths:
        - DeepResearch/src/prompts/**
        - configs/prompts/**

    - component_id: workflow_patterns
      name: Workflow Patterns
      paths:
        - DeepResearch/src/workflow_patterns.py
        - DeepResearch/examples/workflow_patterns_demo.py

    # Specialized Components
    - component_id: bioinformatics
      name: Bioinformatics
      paths:
        - DeepResearch/src/tools/bioinformatics/**
        - DeepResearch/src/agents/bioinformatics_agents.py
        - DeepResearch/src/datatypes/bioinformatics*.py
        - DeepResearch/src/prompts/bioinformatics*.py
        - DeepResearch/src/statemachines/bioinformatics_workflow.py
        - configs/bioinformatics/**
        - tests/test_bioinformatics_tools/**
        - docker/bioinformatics/**

    - component_id: deep_agent
      name: Deep Agent
      paths:
        - DeepResearch/src/agents/deep_agent*.py
        - DeepResearch/src/datatypes/deep_agent*.py
        - DeepResearch/src/prompts/deep_agent*.py
        - DeepResearch/src/statemachines/deep_agent*.py
        - DeepResearch/src/tools/deep_agent*.py
        - configs/deep_agent/**

    - component_id: rag
      name: RAG
      paths:
        - DeepResearch/src/agents/rag_agent.py
        - DeepResearch/src/datatypes/rag.py
        - DeepResearch/src/prompts/rag.py
        - DeepResearch/src/statemachines/rag_workflow.py
        - configs/rag/**

    - component_id: vllm
      name: VLLM Integration
      paths:
        - DeepResearch/src/agents/vllm_agent.py
        - DeepResearch/src/datatypes/vllm*.py
        - DeepResearch/src/prompts/vllm_agent.py
        - configs/vllm/**
        - tests/test_llm_framework/**
        - tests/test_prompts_vllm/**
        - test_artifacts/vllm_tests/**

    - component_id: deepsearch
      name: Deep Search
      paths:
        - DeepResearch/src/tools/deepsearch*.py
        - DeepResearch/src/statemachines/deepsearch_workflow.py
        - configs/deepsearch/**

    # Test Components
    - component_id: test_bioinformatics
      name: Bioinformatics Tests
      paths:
        - tests/test_bioinformatics_tools/**

    - component_id: test_vllm
      name: VLLM Tests
      paths:
        - tests/test_llm_framework/**
        - tests/test_prompts_vllm/**

    - component_id: test_pydantic_ai
      name: Pydantic AI Tests
      paths:
        - tests/test_pydantic_ai/**

    - component_id: test_docker_sandbox
      name: Docker Sandbox Tests
      paths:
        - tests/test_docker_sandbox/**

    - component_id: test_core
      name: Core Tests
      paths:
        - tests/test_*.py

    # Configuration and Documentation
    - component_id: configuration
      name: Configuration
      paths:
        - configs/**
        - pyproject.toml
        - codecov.yml

    - component_id: scripts
      name: Scripts
      paths:
        - DeepResearch/scripts/**
        - scripts/**

    - component_id: docker
      name: Docker
      paths:
        - docker/**

github_checks:
  annotations: true
