site_name: DeepCritical
site_description: Hydra-configured, Pydantic Graph-based deep research workflow
site_author: DeepCritical Team
site_url: https://deepcritical.github.io/DeepCritical/
site_dir: site

repo_name: DeepCritical/DeepCritical
repo_url: https://github.com/DeepCritical/DeepCritical
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search:
      lang: en
  - mermaid2:
      arguments:
        theme: base
        themeVariables:
          primaryColor: '#7c4dff'
          primaryTextColor: '#fff'
          primaryBorderColor: '#7c4dff'
          lineColor: '#7c4dff'
          secondaryColor: '#f8f9fa'
          tertiaryColor: '#fff'
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true
  - mkdocstrings:
      handlers:
        python:
          paths: [., DeepResearch]
          options:
            docstring_style: google
            docstring_section_style: table
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_bases: true
            show_category_heading: true
            show_docstring_attributes: true
            show_docstring_functions: true
            show_docstring_classes: true
            show_docstring_modules: true
            show_if_no_docstring: true
            show_inheritance_diagram: true
            show_labels: true
            show_object_full_path: false
            show_signature: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: DeepCritical
      repo: DeepCritical
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Architecture Overview: architecture/overview.md
    - Configuration: user-guide/configuration.md
    - Flows:
      - PRIME Flow: user-guide/flows/prime.md
      - Bioinformatics Flow: user-guide/flows/bioinformatics.md
      - DeepSearch Flow: user-guide/flows/deepsearch.md
      - Challenge Flow: user-guide/flows/challenge.md
    - Tools:
      - Tool Registry: user-guide/tools/registry.md
      - Bioinformatics Tools: user-guide/tools/bioinformatics.md
      - Search Tools: user-guide/tools/search.md
      - RAG Tools: user-guide/tools/rag.md
  - API Reference:
    - Core Modules: core/index.md
    - Utilities: utilities/index.md
    - Flows: flows/index.md
    - Tools: api/tools.md
    - Tool Overview: tools/index.md
  - Development:
    - Setup: development/setup.md
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - CI/CD: development/ci-cd.md
    - Scripts: development/scripts.md
  - Examples:
    - Basic Usage: examples/basic.md
    - Advanced Workflows: examples/advanced.md
