# Deep Search Flow Configuration
# Based on Jina AI DeepResearch patterns

# Flow metadata
name: "deepsearch"
description: "Deep search workflow with iterative research, reflection, and synthesis"
version: "1.0.0"

# Flow settings
settings:
  enabled: true
  max_execution_time: 300  # 5 minutes
  max_steps: 20
  timeout: 30

  # Parallel execution
  parallel_execution: false
  max_concurrent_operations: 1

  # Error handling
  error_handling:
    max_retries: 3
    retry_delay: 1
    continue_on_error: false

# Flow nodes configuration
nodes:
  initialize:
    type: "InitializeDeepSearch"
    description: "Initialize deep search components and context"
    timeout: 10
    retries: 2

  plan_strategy:
    type: "PlanSearchStrategy"
    description: "Plan search strategy based on question analysis"
    timeout: 15
    retries: 2
    depends_on: ["initialize"]

  execute_search:
    type: "ExecuteSearchStep"
    description: "Execute individual search steps iteratively"
    timeout: 30
    retries: 3
    depends_on: ["plan_strategy"]
    max_iterations: 15

  check_progress:
    type: "CheckSearchProgress"
    description: "Check if search should continue or move to synthesis"
    timeout: 5
    retries: 1
    depends_on: ["execute_search"]

  synthesize:
    type: "SynthesizeResults"
    description: "Synthesize all collected information into comprehensive answer"
    timeout: 20
    retries: 2
    depends_on: ["check_progress"]

  evaluate:
    type: "EvaluateResults"
    description: "Evaluate quality and completeness of results"
    timeout: 15
    retries: 2
    depends_on: ["synthesize"]

  complete:
    type: "CompleteDeepSearch"
    description: "Complete workflow and return final results"
    timeout: 10
    retries: 1
    depends_on: ["evaluate"]

  error_handler:
    type: "DeepSearchError"
    description: "Handle errors and provide error response"
    timeout: 5
    retries: 0

# Flow transitions
transitions:
  - from: "initialize"
    to: "plan_strategy"
    condition: "success"

  - from: "plan_strategy"
    to: "execute_search"
    condition: "success"

  - from: "execute_search"
    to: "check_progress"
    condition: "success"

  - from: "check_progress"
    to: "execute_search"
    condition: "continue_search"

  - from: "check_progress"
    to: "synthesize"
    condition: "synthesize_ready"

  - from: "synthesize"
    to: "evaluate"
    condition: "success"

  - from: "evaluate"
    to: "complete"
    condition: "success"

  # Error transitions
  - from: "initialize"
    to: "error_handler"
    condition: "error"

  - from: "plan_strategy"
    to: "error_handler"
    condition: "error"

  - from: "execute_search"
    to: "error_handler"
    condition: "error"

  - from: "check_progress"
    to: "error_handler"
    condition: "error"

  - from: "synthesize"
    to: "error_handler"
    condition: "error"

  - from: "evaluate"
    to: "error_handler"
    condition: "error"

# Flow parameters
parameters:
  # Input parameters
  input:
    question:
      type: "string"
      required: true
      description: "The question to research"

    max_steps:
      type: "integer"
      default: 20
      min: 1
      max: 50
      description: "Maximum number of search steps"

    token_budget:
      type: "integer"
      default: 10000
      min: 1000
      max: 50000
      description: "Maximum tokens to use"

    search_engines:
      type: "array"
      default: ["google"]
      description: "Search engines to use"

    evaluation_criteria:
      type: "array"
      default: ["definitive", "completeness", "freshness"]
      description: "Evaluation criteria to apply"

  # Output parameters
  output:
    final_answer:
      type: "string"
      description: "The final comprehensive answer"

    confidence_score:
      type: "float"
      description: "Confidence score for the answer"

    quality_metrics:
      type: "object"
      description: "Quality metrics for the search process"

    processing_steps:
      type: "array"
      description: "List of processing steps completed"

    search_summary:
      type: "object"
      description: "Summary of search activities"

# Flow monitoring
monitoring:
  # Metrics to track
  metrics:
    - execution_time
    - steps_completed
    - search_results_count
    - url_visits_count
    - reflection_questions_count
    - confidence_score
    - quality_metrics

  # Alerts
  alerts:
    - condition: "execution_time > 300"
      message: "Deep search execution exceeded 5 minutes"
      level: "warning"

    - condition: "confidence_score < 0.5"
      message: "Low confidence score in deep search results"
      level: "warning"

    - condition: "steps_completed == max_steps"
      message: "Deep search reached maximum steps limit"
      level: "info"

# Flow validation
validation:
  # Input validation
  input_validation:
    question:
      min_length: 10
      max_length: 1000
      pattern: ".*"

    max_steps:
      min: 1
      max: 50

    token_budget:
      min: 1000
      max: 50000

  # Output validation
  output_validation:
    final_answer:
      min_length: 50
      max_length: 10000

    confidence_score:
      min: 0.0
      max: 1.0

# Flow optimization
optimization:
  # Performance optimization
  performance:
    enable_caching: true
    cache_ttl: 3600
    parallel_processing: false

  # Resource optimization
  resources:
    max_memory: "1GB"
    max_cpu: 80
    cleanup_on_completion: true

  # Quality optimization
  quality:
    adaptive_search: true
    dynamic_timeout: true
    quality_threshold: 0.8
