name: 🐛 Bug Report
description: Report a bug or unexpected behavior in DeepCritical
title: "[BUG]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the form below to help us understand and reproduce the issue.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Core Workflow Engine
        - PRIME Flow (Protein Engineering)
        - Bioinformatics Flow (Data Fusion)
        - DeepSearch Flow (Web Research)
        - Challenge Flow (Experimental)
        - Tool Registry
        - Agent System
        - Configuration (Hydra)
        - Pydantic Graph
        - Documentation
        - Installation/Setup
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System crash, data loss)
        - High (Major functionality broken)
        - Medium (Minor functionality affected)
        - Low (Cosmetic issue, minor inconvenience)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        - OS: [e.g., Windows 10, macOS 13.0, Ubuntu 22.04]
        - Python version: [e.g., 3.10.8]
        - DeepCritical version: [e.g., 0.1.0]
        - Installation method: [e.g., uv, pip]
        - Configuration: [e.g., app_mode=single_react, flows.prime.enabled=true]
    validations:
      required: true

  - type: textarea
    id: command_used
    attributes:
      label: Command Used
      description: The exact command that caused the issue
      placeholder: |
        uv run deepresearch question="..." app_mode=single_react
    validations:
      required: true

  - type: textarea
    id: error_logs
    attributes:
      label: Error Logs
      description: Any error messages or logs
      placeholder: |
        Paste any error messages, stack traces, or relevant logs here...
      render: shell

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Relevant configuration files or settings
      placeholder: |
        If applicable, paste relevant configuration snippets here...
      render: yaml

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context about the problem here...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the information requested above
          required: true
        - label: I am willing to help test the fix
          required: false


