blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/DeepCritical/DeepCritical/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/DeepCritical/DeepCritical/wiki
    about: Check our documentation for answers to common questions.
  - name: Security Vulnerability
    url: https://github.com/DeepCritical/DeepCritical/security/advisories/new
    about: Report a security vulnerability privately.
