name: ✨ Feature Request
description: Suggest a new feature or enhancement for DeepCritical
title: "[FEATURE]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Core Workflow Engine
        - PRIME Flow (Protein Engineering)
        - Bioinformatics Flow (Data Fusion)
        - DeepSearch Flow (Web Research)
        - Challenge Flow (Experimental)
        - Tool Registry
        - Agent System
        - Configuration (Hydra)
        - Pydantic Graph
        - Documentation
        - Installation/Setup
        - New Component
        - Other
    validations:
      required: true

  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Tool
        - New Agent
        - New Flow
        - Configuration Enhancement
        - UI/UX Improvement
        - Performance Optimization
        - Integration (External Service)
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        A clear and concise description of what you want to happen.
        Include any specific implementation details if you have them.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        Provide specific examples of how this feature would be used:
        1. Use case 1: ...
        2. Use case 2: ...
        3. Use case 3: ...

  - type: textarea
    id: implementation_notes
    attributes:
      label: Implementation Notes
      description: Any technical considerations or implementation ideas
      placeholder: |
        If you have any technical insights or implementation ideas, please share them here...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking current work)
        - High (Important for workflow)
        - Medium (Nice to have)
        - Low (Future consideration)
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context about the feature request
      placeholder: Add any other context or screenshots about the feature request here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the information requested above
          required: true
        - label: I am willing to help implement this feature
          required: false
        - label: I am willing to help test this feature
          required: false


