# @package _global_

# Comprehensive bioinformatics configuration
# Uses all data sources with lower quality thresholds for maximum coverage

defaults:
  - /bioinformatics/defaults
  - /bioinformatics/data_sources
  - /bioinformatics/agents
  - /bioinformatics/tools
  - /bioinformatics/workflow

# Override for comprehensive settings
data_sources:
  go:
    evidence_codes: ${bioinformatics.evidence_codes.experimental}  # IDA, EXP, IPI
    quality_threshold: ${bioinformatics.quality.minimum_threshold}  # 0.7

  pubmed:
    max_results: ${bioinformatics.pubmed.comprehensive_max_results}  # 100

  geo:
    enabled: true
    include_expression: true

  drugbank:
    enabled: true
    include_targets: true
    include_mechanisms: true

  pdb:
    enabled: true
    include_interactions: true

  intact:
    enabled: true
    confidence_min: ${bioinformatics.intact.low_confidence_min}  # 0.5

fusion:
  quality_threshold: ${bioinformatics.quality.minimum_threshold}  # 0.7
  max_entities: ${bioinformatics.limits.comprehensive_max_entities}  # 2000
  cross_reference_enabled: true

reasoning:
  confidence_threshold: ${bioinformatics.reasoning.default_confidence_threshold}  # 0.7

performance:
  max_concurrent_requests: 8  # Increased for comprehensive processing
