# Loss-driven mode configuration
# Execution driven by loss functions and quality metrics

app_mode: "loss_driven"

primary_orchestrator:
  orchestrator_id: "primary_orchestrator"
  agent_role: "orchestrator_agent"
  model_name: "anthropic:claude-sonnet-4-0"
  max_nested_loops: 10
  coordination_strategy: "adaptive"
  can_spawn_subgraphs: true
  can_spawn_agents: true
  break_conditions:
    - condition_type: "confidence_threshold"
      threshold: 0.95
      operator: ">="
      enabled: true
    - condition_type: "quality_score"
      threshold: 0.9
      operator: ">="
      enabled: true
    - condition_type: "consensus_level"
      threshold: 0.9
      operator: ">="
      enabled: true

nested_react_configs:
  - loop_id: "exploration_loop"
    parent_loop_id: null
    max_iterations: 15
    state_machine_mode: "group_chat"
    subgraphs:
      - "rag_subgraph"
      - "search_subgraph"
    agent_roles:
      - "search_agent"
      - "rag_agent"
      - "explorer_agent"
    tools:
      - "web_search"
      - "rag_query"
      - "exploration_tool"
    priority: 10
    break_conditions:
      - condition_type: "confidence_threshold"
        threshold: 0.7
        operator: ">="
        enabled: true

  - loop_id: "refinement_loop"
    parent_loop_id: "exploration_loop"
    max_iterations: 10
    state_machine_mode: "sequential"
    subgraphs:
      - "code_subgraph"
      - "reasoning_subgraph"
    agent_roles:
      - "code_executor"
      - "reasoning_agent"
      - "refiner_agent"
    tools:
      - "code_sandbox"
      - "reasoning_engine"
      - "refinement_tool"
    priority: 8
    break_conditions:
      - condition_type: "quality_score"
        threshold: 0.8
        operator: ">="
        enabled: true

  - loop_id: "optimization_loop"
    parent_loop_id: "refinement_loop"
    max_iterations: 8
    state_machine_mode: "pipeline"
    subgraphs:
      - "evaluation_subgraph"
    agent_roles:
      - "evaluator"
      - "optimizer_agent"
      - "judge"
    tools:
      - "evaluation_tool"
      - "optimization_tool"
      - "judge_tool"
    priority: 6
    break_conditions:
      - condition_type: "confidence_threshold"
        threshold: 0.9
        operator: ">="
        enabled: true

  - loop_id: "finalization_loop"
    parent_loop_id: "optimization_loop"
    max_iterations: 5
    state_machine_mode: "hierarchical"
    subgraphs:
      - "evaluation_subgraph"
    agent_roles:
      - "coordinator"
      - "finalizer_agent"
      - "judge"
    tools:
      - "finalization_tool"
      - "judge_tool"
      - "quality_assessor"
    priority: 4
    break_conditions:
      - condition_type: "confidence_threshold"
        threshold: 0.95
        operator: ">="
        enabled: true

subgraph_configs:
  - subgraph_id: "rag_subgraph"
    subgraph_type: "rag_subgraph"
    state_machine_path: "DeepResearch.src.statemachines.rag_workflow"
    entry_node: "InitializeRAG"
    exit_node: "GenerateResponse"
    parameters:
      chunk_size: 1000
      chunk_overlap: 200
      top_k: 5
    tools:
      - "rag_query"
      - "document_loader"
    max_execution_time: 120.0
    enabled: true

  - subgraph_id: "search_subgraph"
    subgraph_type: "search_subgraph"
    state_machine_path: "DeepResearch.src.statemachines.search_workflow"
    entry_node: "InitializeSearch"
    exit_node: "GenerateFinalResponse"
    parameters:
      num_results: 10
      chunk_size: 1000
    tools:
      - "web_search"
      - "url_visit"
    max_execution_time: 90.0
    enabled: true

  - subgraph_id: "code_subgraph"
    subgraph_type: "code_subgraph"
    state_machine_path: "DeepResearch.src.statemachines.code_execution_workflow"
    entry_node: "InitializeCode"
    exit_node: "FinalizeCode"
    parameters:
      max_attempts: 3
      timeout: 30
    tools:
      - "code_sandbox"
      - "linter"
    max_execution_time: 60.0
    enabled: true

  - subgraph_id: "reasoning_subgraph"
    subgraph_type: "reasoning_subgraph"
    state_machine_path: "DeepResearch.src.statemachines.reasoning_workflow"
    entry_node: "InitializeReasoning"
    exit_node: "SynthesizeReasoning"
    parameters:
      reasoning_type: "scientific"
      confidence_threshold: 0.8
    tools:
      - "reasoning_engine"
      - "evidence_evaluator"
    max_execution_time: 90.0
    enabled: true

  - subgraph_id: "evaluation_subgraph"
    subgraph_type: "evaluation_subgraph"
    state_machine_path: "DeepResearch.src.statemachines.evaluation_workflow"
    entry_node: "InitializeEvaluation"
    exit_node: "FinalizeEvaluation"
    parameters:
      evaluation_criteria: ["quality", "accuracy", "completeness", "clarity"]
      scoring_scale: "1-10"
    tools:
      - "evaluation_tool"
      - "judge_tool"
      - "quality_assessor"
    max_execution_time: 60.0
    enabled: true

loss_functions:
  - condition_type: "confidence_threshold"
    threshold: 0.95
    operator: ">="
    enabled: true
  - condition_type: "quality_score"
    threshold: 0.9
    operator: ">="
    enabled: true
  - condition_type: "consensus_level"
    threshold: 0.9
    operator: ">="
    enabled: true
  - condition_type: "custom_loss"
    threshold: 0.85
    operator: ">="
    enabled: true
    custom_function: "combined_quality_metric"

global_break_conditions:
  - condition_type: "time_limit"
    threshold: 1200.0
    operator: ">="
    enabled: true
  - condition_type: "iteration_limit"
    threshold: 50
    operator: ">="
    enabled: true
  - condition_type: "confidence_threshold"
    threshold: 0.98
    operator: ">="
    enabled: true

execution_strategy: "loss_driven"
max_total_iterations: 50
max_total_time: 1200.0






