# Neo4j Vector Store Configuration
store_type: "neo4j"
connection_string: "bolt://localhost:7687"
host: "localhost"
port: 7687
database: "neo4j"
collection_name: "vector_index"
api_key: null
embedding_dimension: 1536
distance_metric: "cosine"
index_type: "hnsw"
username: "neo4j"
password: "password"
