# PostgreSQL with pgvector Configuration
store_type: "postgres"
connection_string: "postgresql://postgres:postgres@localhost:5432/rag_db"
host: "localhost"
port: 5432
database: "rag_db"
collection_name: "documents"
api_key: null
embedding_dimension: 1536
distance_metric: "cosine"
index_type: "hnsw"
username: "postgres"
password: "postgres"
