# @package _global_

defaults:
  - challenge: default
  - workflow_orchestration: default
  - _self_
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default

# Main configuration
question: "What is machine learning and how does it work?"

# Basic settings
retries: 3
manual_confirm: false

# Challenge configuration
challenge:
  enabled: false
  name: "Research Challenge"
  domain: "general"

# Workflow orchestration configuration
workflow_orchestration:
  enabled: true  # Enable the primary REACT workflow orchestration
  primary_workflow:
    workflow_type: primary_react
    name: main_research_workflow
    enabled: true
    priority: 10
    max_retries: 3
    timeout: 300.0
    parameters:
      max_iterations: 10
      enable_reflection: true
      enable_self_correction: true
      coordination_strategy: adaptive
      enable_sub_workflow_spawning: true
      enable_dynamic_composition: true
      enable_multi_agent_coordination: true

# Legacy flow configurations (for backward compatibility)
flows:
  prime:
    enabled: false
  bioinformatics:
    enabled: false
  rag:
    enabled: false
  deepsearch:
    enabled: false
  node_example:
    enabled: false
  jina_ai:
    enabled: false

# Output configuration
outputs:
  enable_hypothesis_datasets: true
  enable_testing_environments: true
  enable_reasoning_results: true
  enable_automated_datasets: true
  output_format: structured_json
  include_metadata: true
  include_execution_traces: true

# Performance settings
performance:
  enable_parallel_execution: true
  enable_result_caching: true
  cache_ttl: 3600  # 1 hour
  enable_workflow_optimization: true

# VLLM test configuration
vllm_tests:
  enabled: false  # Disabled by default for CI safety
  run_in_ci: false  # Never run in CI
  require_manual_confirmation: false

  # Test execution settings
  execution_strategy: sequential
  max_concurrent_tests: 1  # Single instance optimization
  enable_module_batching: true
  module_batch_size: 3

  # Test data and validation
  use_realistic_dummy_data: true
  enable_prompt_validation: true
  enable_response_validation: true

  # Artifact configuration
  artifacts:
    enabled: true
    base_directory: "test_artifacts/vllm_tests"
    save_individual_results: true
    save_module_summaries: true
    save_global_summary: true

  # Performance monitoring
  monitoring:
    enabled: true
    track_execution_times: true
    track_memory_usage: true
    max_execution_time_per_module: 300  # seconds

  # Error handling
  error_handling:
    graceful_degradation: true
    continue_on_module_failure: true
    retry_failed_prompts: true
    max_retries_per_prompt: 2
