# OpenAI LLM Configuration
model_type: "openai"
model_name: "gpt-4"
host: "api.openai.com"
port: 443
api_key: ${oc.env:OPENAI_API_KEY,null}
max_tokens: 2048
temperature: 0.7
top_p: 0.9
frequency_penalty: 0.0
presence_penalty: 0.0
stop: null
stream: false
